import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: '#0f172a',
  },
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#0f172a',
  },
  header: {
    marginBottom: 32,
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#f1f5f9',
    marginBottom: 12,
    textAlign: 'center',
  },
  description: {
    fontSize: 16,
    color: '#94a3b8',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  primaryButton: {
    backgroundColor: '#6366f1',
    paddingVertical: 18,
    paddingHorizontal: 32,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    marginBottom: 24,
  },
  primaryButtonIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  uploadSection: {
    marginBottom: 24,
  },
  uploadButton: {
    backgroundColor: '#6366f1',
    paddingVertical: 18,
    paddingHorizontal: 32,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    cursor: 'pointer',
  },
  uploadIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  uploadText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  disabledButton: {
    opacity: 0.5,
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 24,
    backgroundColor: '#1e293b',
    borderRadius: 12,
    marginBottom: 24,
  },
  loadingText: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 12,
  },
  errorBox: {
    backgroundColor: '#7f1d1d',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dc2626',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  errorIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  errorText: {
    color: '#fecaca',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  backButton: {
    backgroundColor: '#334155',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  backButtonText: {
    color: '#94a3b8',
    fontSize: 16,
    fontWeight: '600',
  },
  cameraContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  cameraOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 60,
    paddingBottom: 48,
    paddingHorizontal: 24,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  instructionBox: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 20,
    borderRadius: 16,
    alignItems: 'center',
  },
  instructions: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  instructionsSub: {
    color: '#cbd5e1',
    textAlign: 'center',
    fontSize: 14,
  },
  controlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cancelBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '400',
  },
  captureBtn: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  capturingBtn: {
    opacity: 0.6,
  },
  captureInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#6366f1',
  },
  resultsContainer: {
    gap: 16,
    marginBottom: 24,
  },
  riskCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  cardTitle: {
    color: '#f1f5f9',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
  },
  riskLevelContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  riskLevelLabel: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 12,
  },
  riskBadge: {
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  riskLOW: { backgroundColor: '#166534' },
  riskMODERATE: { backgroundColor: '#854d0e' },
  riskHIGH: { backgroundColor: '#7f1d1d' },
  riskBadgeText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  confidenceBar: { marginTop: 16 },
  confidenceLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  progressBarBg: {
    height: 8,
    backgroundColor: '#0f172a',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#6366f1',
    borderRadius: 4,
  },
  confidenceValue: {
    color: '#f1f5f9',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'right',
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  scoreLabel: { color: '#94a3b8', fontSize: 14, fontWeight: '500' },
  scoreValue: { color: '#f1f5f9', fontSize: 20, fontWeight: '700' },
  mapCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
  },
  mapContainer: { overflow: 'hidden', borderRadius: 12 },
  coordContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0f172a',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  coordLabel: { color: '#94a3b8', fontSize: 13, fontWeight: '600' },
  coordValue: {
    color: '#f1f5f9',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  mapVisual: {
    backgroundColor: '#0f172a',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapVisualIcon: { fontSize: 64, marginBottom: 12 },
  mapVisualText: { color: '#94a3b8', fontSize: 14, fontWeight: '600', marginBottom: 16 },
  openMapButton: {
    backgroundColor: '#6366f1',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  openMapIcon: { fontSize: 16 },
  openMapText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  weatherCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
  },
  weatherContent: { gap: 16 },
  weatherRow: { flexDirection: 'row', justifyContent: 'space-around' },
  weatherItem: { alignItems: 'center' },
  weatherIcon: { fontSize: 32, marginBottom: 8 },
  weatherValue: { color: '#f1f5f9', fontSize: 20, fontWeight: '700', marginBottom: 4 },
  weatherLabel: { color: '#94a3b8', fontSize: 12, fontWeight: '500' },
  weatherDescription: { backgroundColor: '#0f172a', padding: 12, borderRadius: 8, alignItems: 'center' },
  weatherDescText: { color: '#cbd5e1', fontSize: 14, fontWeight: '500', textTransform: 'capitalize' },
  slipsCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
  },
  slipsHeader: { alignItems: 'center', marginBottom: 20 },
  slipsCount: { color: '#f59e0b', fontSize: 48, fontWeight: '700', marginBottom: 4 },
  slipsCountLabel: { color: '#94a3b8', fontSize: 14, fontWeight: '500' },
  slipsScrollView: { maxHeight: 400 },
  slipsList: { gap: 12 },
  slipItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  slipDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#f59e0b', marginTop: 8, marginRight: 12 },
  slipInfo: { flex: 1, gap: 8 },
  slipHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  slipTime: { color: '#f1f5f9', fontSize: 14, fontWeight: '700' },
  slipTimeDetail: { color: '#94a3b8', fontSize: 12, fontWeight: '500' },
  slipCoords: {
    color: '#6366f1',
    fontSize: 11,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginBottom: 4,
  },
  slipWeatherDetails: { backgroundColor: '#1e293b', padding: 10, borderRadius: 8, gap: 6 },
  weatherDetailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  weatherDetailItem: { color: '#cbd5e1', fontSize: 11, fontWeight: '500', flex: 1 },
  slipFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#334155' },
  slipVehicle: { color: '#94a3b8', fontSize: 11, fontWeight: '600' },
  tapToView: { color: '#6366f1', fontSize: 11, fontWeight: '700' },
  factorsCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
  },
  factorsList: { gap: 16 },
  factorRow: { gap: 8 },
  factorLabel: { color: '#94a3b8', fontSize: 13, fontWeight: '600', marginBottom: 4 },
  factorBar: { height: 24, backgroundColor: '#0f172a', borderRadius: 6, overflow: 'hidden' },
  factorFill: { height: '100%', borderRadius: 6 },
  factorValue: { color: '#f1f5f9', fontSize: 12, fontWeight: '700', textAlign: 'right', marginTop: 4 },
  gradientCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
  },
  gradientGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  gradientItem: { flex: 1, backgroundColor: '#0f172a', padding: 16, borderRadius: 12, alignItems: 'center' },
  gradientValue: { color: '#6366f1', fontSize: 24, fontWeight: '700', marginBottom: 8 },
  gradientLabel: { color: '#94a3b8', fontSize: 11, fontWeight: '500', textAlign: 'center' },
});
