import { StyleSheet } from 'react-native';
import { theme } from './theme';

export const dashboardStyles = StyleSheet.create({
  header: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.textPrimary,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 16,
    color: theme.textSecondary,
  },
  logoutButton: {
    position: 'absolute',
    right: 24,
    top: 36,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#4b5563',
  },
  logoutText: {
    color: theme.textSecondary,
    fontSize: 12,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  trackingCard: {
    width: '100%',
    flex: 0.4,
    borderRadius: 20,
    backgroundColor: theme.card,
    marginBottom: 24,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  road: {
    position: 'absolute',
    width: 120,
    height: '120%',
    backgroundColor: '#020617',
    borderRadius: 999,
    borderColor: '#111827',
    borderWidth: 2,
  },
  laneDivider: {
    position: 'absolute',
    left: '50%',
    top: 0,
    width: 2,
    height: '100%',
    backgroundColor: '#4b5563',
    transform: [{ translateX: -1 }],
  },
  vehicleIcon: {
    width: 36,
    height: 60,
    borderRadius: 12,
    backgroundColor: theme.primary,
    borderWidth: 3,
    borderColor: '#bbf7d0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  signalDotOuter: {
    position: 'absolute',
    right: 28,
    top: 32,
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: theme.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  signalDotInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.secondary,
  },
  description: {
    fontSize: 14,
    color: theme.textSecondary,
    marginBottom: 32,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  button: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButton: {
    backgroundColor: theme.primary,
  },
  secondaryButton: {
    backgroundColor: theme.secondary,
  },
  buttonText: {
    color: '#0b1120',
    fontSize: 16,
    fontWeight: '600',
  },
});
